name: Tests
on:
  pull_request:
  push: { branches: [main] }

jobs:
  source_e2e_tests:
    name: Run Source E2E Tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
    strategy:
      fail-fast: false
      matrix:
        adapter: [Appwrite, Supabase, NHost]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bring up services
        run: docker-compose up -d --build

      - name: Run ${{matrix.adapter}} Tests
        run: |
          docker compose exec tests php ./vendor/bin/phpunit /usr/src/code/tests/Migration/E2E/Sources/${{matrix.adapter}}Test.php