name: Tests
on:
  pull_request:
  push: { branches: [main] }

jobs:
  tests:
    name: Run Test Suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          docker-compose up -d --build && docker compose exec tests php ./vendor/bin/phpunit