name: Tests
on:
  pull_request:
  push: { branches: [main] }

jobs:
  mockapi:
    name: Run Mock API Test Suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bring up services
        run: docker-compose up -d --build --detach --wait --wait-timeout 180 && sleep 5

      - name: Run Supabase Test Suite
        run: |
          docker compose exec tests php ./vendor/bin/phpunit --group Supabase

      - name: Run NHost Test Suite
        run: |
          docker compose exec tests php ./vendor/bin/phpunit --group NHost
  appwrite:
    name: Run Appwrite Test Suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Appwrite
        run: |
          git clone https://github.com/appwrite/appwrite.git
          cd appwrite
          docker-compose up -d --build

      - name: Run Appwrite Test Suite
        run: |
          docker compose exec tests php ./vendor/bin/phpunit --group Appwrite
