name: Tests
on:
  pull_request:
  push: { branches: [main] }

jobs:
  tests:
    name: Run Test Suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bring up services
        run: docker-compose up -d --build && sleep 5

      - name: Run Supabase Test Suite
        run: |
          docker compose exec tests php ./vendor/bin/phpunit --group Supabase

      - name: Run NHost Test Suite
        run: |
          docker compose exec tests php ./vendor/bin/phpunit --group NHost